-- 코드를 입력하세요
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID IN (SELECT I.ANIMAL_ID
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE LEFT(I.SEX_UPON_INTAKE, 6) = 'Intact')
AND (LEFT(SEX_UPON_OUTCOME, 8) = 'Neutered'
OR LEFT(SEX_UPON_OUTCOME, 6) = 'Spayed')
;