WITH RECURSIVE GENES AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
      FROM ECOLI_DATA
     WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1 AS GENERATION
      FROM ECOLI_DATA E
      JOIN GENES G
        ON E.PARENT_ID = G.ID
)
SELECT COUNT(*) AS COUNT, G.GENERATION
  FROM GENES G
  LEFT OUTER JOIN ECOLI_DATA C
    ON G.ID = C.PARENT_ID
  WHERE C.ID IS NULL
  GROUP BY G.GENERATION