-- 코드를 입력하세요
SELECT A.FLAVOR FROM (SELECT J.FLAVOR, F.TOTAL_ORDER + SUM(J.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F JOIN JULY J
ON F.FLAVOR = J.FLAVOR
GROUP BY J.FLAVOR
ORDER BY TOTAL_ORDER DESC
LIMIT 3) AS A;

