-- 코드를 입력하세요
WITH RECURSIVE CTE AS(
SELECT 0 AS HOUR
UNION ALL
SELECT HOUR +1 FROM CTE WHERE HOUR BETWEEN 0 AND 22)
SELECT C.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM CTE C LEFT JOIN ANIMAL_OUTS A
ON C.HOUR = HOUR(A.DATETIME)
GROUP BY C.HOUR
ORDER BY C.HOUR;